# Generated by Django 3.2.4 on 2021-06-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='clientes/fotografia/')),
                ('direccion', models.CharField(max_length=50)),
                ('tipo', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'NORMAL'), (2, 'PLATA'), (3, 'ORO'), (4, 'PLATINO')], null=True)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
