# Generated by Django 3.2.4 on 2021-06-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=50)),
                ('articulos', models.ManyToManyField(to='articulos.Articulos')),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
